import { describe, it, expect } from "vitest";
import playerStandardManual from "../fixtures/player-standard-manual.json";
import timedtextNonLatinAsr from "../fixtures/timedtext-non-latin-asr.json";
import {
  buildTranscript,
  calculateClampedEndTime,
  escapeCsvField,
  formatToJson,
  formatToCsv,
  formatToMarkdown,
  formatToSrt,
  formatToTxt,
  formatToVtt,
  formatTranscript,
  groupSegmentsIntoParagraphs,
  type Transcript,
} from "../src/index.js";

const sampleTranscript: Transcript = {
  videoId: "dQw4w9WgXcQ",
  title: "Never Gonna Give You Up",
  channelName: "Rick Astley",
  language: "en",
  isAutoGenerated: false,
  segments: [
    {
      start: 0,
      duration: 2.5,
      text: "We're no strangers to love",
    },
    {
      start: 3.0,
      duration: 2.0,
      text: "You know the rules and so do I",
    },
    {
      start: 8.0,
      duration: 3.0,
      text: "A full commitment's what I'm thinking of",
    },
  ],
};

describe("formatters", () => {
  describe("escapeCsvField", () => {
    it("returns plain text unchanged", () => {
      expect(escapeCsvField("hello world")).toBe("hello world");
    });

    it("escapes fields containing commas with quotes", () => {
      expect(escapeCsvField("hello, world")).toBe('"hello, world"');
    });

    it("escapes fields containing quotes by doubling them and enclosing in quotes", () => {
      expect(escapeCsvField('he said "hello"')).toBe('"he said ""hello"""');
    });

    it("escapes fields containing newlines or carriage returns", () => {
      expect(escapeCsvField("line 1\nline 2")).toBe('"line 1\nline 2"');
      expect(escapeCsvField("line 1\r\nline 2")).toBe('"line 1\r\nline 2"');
    });

    it("escapes fields containing commas, quotes, and newlines together", () => {
      expect(escapeCsvField('hello, "world"\nnew line')).toBe(
        '"hello, ""world""\nnew line"'
      );
    });
  });

  describe("calculateClampedEndTime", () => {
    it("returns raw end time for last segment", () => {
      const segs = [{ start: 10, duration: 5, text: "Last" }];
      expect(calculateClampedEndTime(segs, 0)).toBe(15);
    });

    it("does not clamp when there is no overlap", () => {
      const segs = [
        { start: 0, duration: 2, text: "First" },
        { start: 5, duration: 2, text: "Second" },
      ];
      expect(calculateClampedEndTime(segs, 0)).toBe(2);
    });

    it("clamps end time to next segment start time when overlapping", () => {
      const segs = [
        { start: 0, duration: 5, text: "First (overlaps)" },
        { start: 3, duration: 2, text: "Second" },
      ];
      expect(calculateClampedEndTime(segs, 0)).toBe(3);
    });

    it("ensures clamped end time is never less than start time", () => {
      const segs = [
        { start: 5, duration: 2, text: "First" },
        { start: 2, duration: 2, text: "Second (out of order)" },
      ];
      expect(calculateClampedEndTime(segs, 0)).toBe(5);
    });
  });

  describe("groupSegmentsIntoParagraphs", () => {
    it("returns empty array for empty segments", () => {
      expect(groupSegmentsIntoParagraphs([])).toEqual([]);
    });

    it("keeps segments in same paragraph when gap <= 2.0s", () => {
      const segs = [
        { start: 0, duration: 2.0, text: "Seg 1" }, // ends at 2.0
        { start: 2.5, duration: 1.0, text: "Seg 2" }, // gap = 0.5s <= 2.0s
        { start: 5.5, duration: 1.0, text: "Seg 3" }, // gap = 2.0s <= 2.0s
      ];
      const paragraphs = groupSegmentsIntoParagraphs(segs);
      expect(paragraphs).toHaveLength(1);
      expect(paragraphs[0]).toHaveLength(3);
    });

    it("splits into new paragraph when gap > 2.0s", () => {
      const segs = [
        { start: 0, duration: 2.0, text: "Seg 1" }, // ends at 2.0
        { start: 4.1, duration: 1.0, text: "Seg 2" }, // gap = 2.1s > 2.0s
      ];
      const paragraphs = groupSegmentsIntoParagraphs(segs);
      expect(paragraphs).toHaveLength(2);
      expect(paragraphs[0]?.[0]?.text).toBe("Seg 1");
      expect(paragraphs[1]?.[0]?.text).toBe("Seg 2");
    });
  });

  describe("formatToTxt", () => {
    it("returns empty string when transcript has no segments", () => {
      const empty: Transcript = { ...sampleTranscript, segments: [] };
      expect(formatToTxt(empty)).toBe("");
    });

    it("formats plain text with paragraph breaks on gaps > 2s without timestamps", () => {
      // Seg 0: ends at 2.5. Seg 1 starts at 3.0 (gap = 0.5s -> same paragraph)
      // Seg 1: ends at 5.0. Seg 2 starts at 8.0 (gap = 3.0s > 2s -> new paragraph)
      const txt = formatToTxt(sampleTranscript);
      expect(txt).toBe(
        "We're no strangers to love You know the rules and so do I\n\nA full commitment's what I'm thinking of"
      );
    });

    it("formats with [mm:ss] prefix when includeTimestamps is true", () => {
      const txt = formatToTxt(sampleTranscript, { includeTimestamps: true });
      expect(txt).toBe(
        "[00:00] We're no strangers to love\n[00:03] You know the rules and so do I\n\n[00:08] A full commitment's what I'm thinking of"
      );
    });
  });

  describe("formatToJson", () => {
    it("formats transcript as 2-space indented pretty-printed JSON", () => {
      const json = formatToJson(sampleTranscript);
      expect(json).toBe(JSON.stringify(sampleTranscript, null, 2));
      const parsed = JSON.parse(json);
      expect(parsed).toEqual(sampleTranscript);
    });
  });

  describe("formatToCsv", () => {
    it("formats transcript as CSV with header and RFC 4180 escaping", () => {
      const transcriptWithQuotes: Transcript = {
        ...sampleTranscript,
        segments: [
          { start: 0, duration: 2, text: "Hello, world" },
          { start: 3, duration: 1.5, text: 'He said "hi"' },
          { start: 6, duration: 2, text: "Simple" },
        ],
      };

      const csv = formatToCsv(transcriptWithQuotes);
      const lines = csv.split("\n");

      expect(lines[0]).toBe("start,duration,text");
      expect(lines[1]).toBe('0,2,"Hello, world"');
      expect(lines[2]).toBe('3,1.5,"He said ""hi"""');
      expect(lines[3]).toBe("6,2,Simple");
    });
  });

  describe("formatToSrt", () => {
    it("returns empty string when transcript has no segments", () => {
      const empty: Transcript = { ...sampleTranscript, segments: [] };
      expect(formatToSrt(empty)).toBe("");
    });

    it("formats 1-based index, HH:MM:SS,mmm timing, and blank line between cues", () => {
      const srt = formatToSrt(sampleTranscript);
      expect(srt).toBe(
        "1\n" +
          "00:00:00,000 --> 00:00:02,500\n" +
          "We're no strangers to love\n\n" +
          "2\n" +
          "00:00:03,000 --> 00:00:05,000\n" +
          "You know the rules and so do I\n\n" +
          "3\n" +
          "00:00:08,000 --> 00:00:11,000\n" +
          "A full commitment's what I'm thinking of\n"
      );
    });

    it("clamps end times to prevent cue overlap", () => {
      const overlapping: Transcript = {
        ...sampleTranscript,
        segments: [
          { start: 0, duration: 5, text: "Cue 1 (overlaps into Cue 2)" },
          { start: 3, duration: 4, text: "Cue 2 (overlaps into Cue 3)" },
          { start: 6, duration: 2, text: "Cue 3" },
        ],
      };

      const srt = formatToSrt(overlapping);
      expect(srt).toContain("00:00:00,000 --> 00:00:03,000\nCue 1");
      expect(srt).toContain("00:00:03,000 --> 00:00:06,000\nCue 2");
      expect(srt).toContain("00:00:06,000 --> 00:00:08,000\nCue 3");
    });
  });

  describe("formatToVtt", () => {
    it("returns WEBVTT header for empty transcript", () => {
      const empty: Transcript = { ...sampleTranscript, segments: [] };
      expect(formatToVtt(empty)).toBe("WEBVTT\n");
    });

    it("formats with WEBVTT header and dot separator for milliseconds", () => {
      const vtt = formatToVtt(sampleTranscript);
      expect(vtt).toBe(
        "WEBVTT\n\n" +
          "1\n" +
          "00:00:00.000 --> 00:00:02.500\n" +
          "We're no strangers to love\n\n" +
          "2\n" +
          "00:00:03.000 --> 00:00:05.000\n" +
          "You know the rules and so do I\n\n" +
          "3\n" +
          "00:00:08.000 --> 00:00:11.000\n" +
          "A full commitment's what I'm thinking of\n"
      );
    });

    it("clamps overlapping cues in VTT", () => {
      const overlapping: Transcript = {
        ...sampleTranscript,
        segments: [
          { start: 0, duration: 4, text: "Cue 1" },
          { start: 2.5, duration: 3, text: "Cue 2" },
        ],
      };
      const vtt = formatToVtt(overlapping);
      expect(vtt).toContain("00:00:00.000 --> 00:00:02.500\nCue 1");
      expect(vtt).toContain("00:00:02.500 --> 00:00:05.500\nCue 2");
    });
  });

  describe("formatToMarkdown", () => {
    it("formats title header, metadata block, and prose body", () => {
      const md = formatToMarkdown(sampleTranscript);
      expect(md).toBe(
        "# Never Gonna Give You Up\n\n" +
          "- **Channel:** Rick Astley\n" +
          "- **Language:** en\n\n" +
          "We're no strangers to love You know the rules and so do I\n\n" +
          "A full commitment's what I'm thinking of"
      );
    });

    it("handles empty transcript segments in Markdown", () => {
      const empty: Transcript = { ...sampleTranscript, segments: [] };
      const md = formatToMarkdown(empty);
      expect(md).toBe(
        "# Never Gonna Give You Up\n\n" +
          "- **Channel:** Rick Astley\n" +
          "- **Language:** en"
      );
    });
  });

  describe("formatTranscript dispatcher", () => {
    it("dispatches correctly to each of the 6 formats", () => {
      expect(formatTranscript(sampleTranscript, "txt")).toBe(
        formatToTxt(sampleTranscript)
      );
      expect(
        formatTranscript(sampleTranscript, "txt", { includeTimestamps: true })
      ).toBe(formatToTxt(sampleTranscript, { includeTimestamps: true }));
      expect(formatTranscript(sampleTranscript, "json")).toBe(
        formatToJson(sampleTranscript)
      );
      expect(formatTranscript(sampleTranscript, "csv")).toBe(
        formatToCsv(sampleTranscript)
      );
      expect(formatTranscript(sampleTranscript, "srt")).toBe(
        formatToSrt(sampleTranscript)
      );
      expect(formatTranscript(sampleTranscript, "vtt")).toBe(
        formatToVtt(sampleTranscript)
      );
      expect(formatTranscript(sampleTranscript, "markdown")).toBe(
        formatToMarkdown(sampleTranscript)
      );
    });
  });

  describe("real fixture formatting", () => {
    it("formats realistic non-Latin fixture across all formats cleanly", () => {
      const result = buildTranscript({
        playerPayload: playerStandardManual,
        timedTextPayload: timedtextNonLatinAsr,
        preferredLanguage: "en",
      });

      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      const transcript = result.value;

      // TXT
      const txt = formatToTxt(transcript);
      expect(txt.length).toBeGreaterThan(0);
      expect(txt).toContain("こんにちは、皆さん！");

      // TXT with timestamps
      const txtTimestamps = formatToTxt(transcript, {
        includeTimestamps: true,
      });
      expect(txtTimestamps).toContain("[00:01] こんにちは、皆さん！");

      // JSON
      const json = formatToJson(transcript);
      expect(JSON.parse(json)).toEqual(transcript);

      // CSV
      const csv = formatToCsv(transcript);
      expect(csv.startsWith("start,duration,text\n")).toBe(true);
      expect(csv).toContain("こんにちは、皆さん！");

      // SRT
      const srt = formatToSrt(transcript);
      expect(srt.startsWith("1\n00:00:01,200 --> ")).toBe(true);
      expect(srt).toContain("こんにちは、皆さん！");

      // VTT
      const vtt = formatToVtt(transcript);
      expect(vtt.startsWith("WEBVTT\n\n1\n00:00:01.200 --> ")).toBe(true);
      expect(vtt).toContain("こんにちは、皆さん！");

      // Markdown
      const md = formatToMarkdown(transcript);
      expect(md.startsWith("# Me at the zoo\n\n- **Channel:** jawed\n- **Language:** en\n\n")).toBe(
        true
      );
      expect(md).toContain("こんにちは、皆さん！");
    });
  });
});
