import { describe, it, expect } from "vitest";
import { createJobItem, type Transcript } from "../src/index.js";

describe("core package", () => {
  it("creates a pending job item", () => {
    const item = createJobItem("vid123", "Sample Video");
    expect(item).toEqual({
      videoId: "vid123",
      title: "Sample Video",
      status: "pending",
    });
  });

  it("conforms to transcript type model", () => {
    const transcript: Transcript = {
      videoId: "vid123",
      title: "Sample Video",
      channelName: "Test Channel",
      language: "en",
      isAutoGenerated: false,
      segments: [
        {
          start: 0,
          duration: 2.5,
          text: "Hello world",
        },
      ],
    };
    expect(transcript.segments).toHaveLength(1);
    expect(transcript.segments[0]?.text).toBe("Hello world");
  });
});
