import { describe, it, expect } from "vitest";
import playerStandardManual from "../fixtures/player-standard-manual.json";
import timedtextNonLatinAsr from "../fixtures/timedtext-non-latin-asr.json";
import {
  buildTranscript,
  createJobItem,
  createExtractionError,
  EXTRACTION_ERROR_MESSAGES,
  type Transcript,
} from "../src/index.js";

describe("core package", () => {
  it("creates a pending job item", () => {
    const item = createJobItem("vid123", "Sample Video");
    expect(item).toEqual({
      videoId: "vid123",
      title: "Sample Video",
      status: "pending",
    });
  });

  it("conforms to transcript type model", () => {
    const transcript: Transcript = {
      videoId: "vid123",
      title: "Sample Video",
      channelName: "Test Channel",
      language: "en",
      isAutoGenerated: false,
      segments: [
        {
          start: 0,
          duration: 2.5,
          text: "Hello world",
        },
      ],
    };
    expect(transcript.segments).toHaveLength(1);
    expect(transcript.segments[0]?.text).toBe("Hello world");
  });

  it("maps error taxonomy correctly to UI messages", () => {
    const error = createExtractionError("NO_CAPTIONS");
    expect(error).toEqual({
      code: "NO_CAPTIONS",
      message: "No transcript available",
    });

    expect(EXTRACTION_ERROR_MESSAGES.PRIVATE_OR_MEMBERS).toBe(
      "Video not accessible"
    );
    expect(EXTRACTION_ERROR_MESSAGES.AGE_RESTRICTED).toBe(
      "Age-restricted video"
    );
    expect(EXTRACTION_ERROR_MESSAGES.LIVE_STREAM).toBe("Live stream — skipped");
    expect(EXTRACTION_ERROR_MESSAGES.RATE_LIMITED).toBe(
      "Rate limited, try again later"
    );
    expect(EXTRACTION_ERROR_MESSAGES.PARSE_ERROR).toBe(
      "Could not parse response"
    );
    expect(EXTRACTION_ERROR_MESSAGES.UNKNOWN).toBe("Unexpected error");
  });

  it("builds a full Transcript object combining player and timedtext payloads", () => {
    const result = buildTranscript({
      playerPayload: playerStandardManual,
      timedTextPayload: timedtextNonLatinAsr,
      preferredLanguage: "en",
    });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    const transcript = result.value;
    expect(transcript.videoId).toBe("jNQXAC9IVRw");
    expect(transcript.title).toBe("Me at the zoo");
    expect(transcript.channelName).toBe("jawed");
    expect(transcript.language).toBe("en");
    expect(transcript.isAutoGenerated).toBe(false);
    expect(transcript.segments.length).toBeGreaterThan(0);
    expect(transcript.segments[0]?.text).toBe("こんにちは、皆さん！");
  });
});
