import { describe, it, expect } from "vitest";
import playerStandardManual from "../fixtures/player-standard-manual.json";
import playerNoCaptions from "../fixtures/player-no-captions.json";
import {
  parsePlayerResponse,
  extractCaptionTracks,
  extractVideoMetadata,
} from "../src/player-parser.js";

describe("player-parser", () => {
  describe("real fixture: player-standard-manual.json", () => {
    it("extracts metadata and manual caption tracks successfully", () => {
      const result = parsePlayerResponse(playerStandardManual);

      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.metadata).toEqual({
        videoId: "jNQXAC9IVRw",
        title: "Me at the zoo",
        channelName: "jawed",
      });

      expect(result.value.captionTracks).toHaveLength(2);
      expect(result.value.defaultCaptionTrackIndex).toBe(0);

      const track0 = result.value.captionTracks[0];
      expect(track0?.languageCode).toBe("en");
      expect(track0?.name).toBe("English");
      expect(track0?.isAutoGenerated).toBe(false);
      expect(track0?.isDefault).toBe(true);
      expect(track0?.baseUrl).toContain("api/timedtext");

      const track1 = result.value.captionTracks[1];
      expect(track1?.languageCode).toBe("de");
      expect(track1?.name).toBe("German");
      expect(track1?.isAutoGenerated).toBe(false);
      expect(track1?.isDefault).toBe(false);
    });
  });

  describe("real fixture: player-no-captions.json", () => {
    it("returns typed NO_CAPTIONS error", () => {
      const result = parsePlayerResponse(playerNoCaptions);

      expect(result.ok).toBe(false);
      if (result.ok) {
        return;
      }

      expect(result.error.code).toBe("NO_CAPTIONS");
      expect(result.error.message).toBe("No transcript available");
    });
  });

  describe("playability error taxonomy", () => {
    it("identifies live stream videos", () => {
      const livePayload = {
        videoDetails: {
          videoId: "live123",
          title: "Live Event",
          author: "Streamer",
          isLiveContent: true,
        },
        playabilityStatus: {
          status: "OK",
        },
      };

      const result = parsePlayerResponse(livePayload);
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe("LIVE_STREAM");
        expect(result.error.message).toBe("Live stream — skipped");
      }
    });

    it("identifies age-restricted videos", () => {
      const ageRestrictedPayload = {
        videoDetails: {
          videoId: "age123",
          title: "Mature Content",
          author: "Creator",
        },
        playabilityStatus: {
          status: "LOGIN_REQUIRED",
          reason: "Sign in to confirm your age",
        },
      };

      const result = parsePlayerResponse(ageRestrictedPayload);
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe("AGE_RESTRICTED");
        expect(result.error.message).toBe("Age-restricted video");
      }
    });

    it("identifies private or members-only videos", () => {
      const privatePayload = {
        videoDetails: {
          videoId: "priv123",
          title: "Private Video",
          author: "Creator",
          isPrivate: true,
        },
        playabilityStatus: {
          status: "LOGIN_REQUIRED",
          reason: "This video is private",
        },
      };

      const result = parsePlayerResponse(privatePayload);
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe("PRIVATE_OR_MEMBERS");
        expect(result.error.message).toBe("Video not accessible");
      }
    });
  });

  describe("defensive parsing without fixed index paths", () => {
    it("locates captionTracks and metadata in unconventional or deeply nested paths", () => {
      const deeplyNestedPayload = {
        arbitraryWrapper: {
          nestedLevel2: {
            videoDetails: {
              videoId: "deep123",
              title: "Deep Title",
              author: "Deep Author",
            },
            deepContainer: {
              captionTracks: [
                {
                  baseUrl: "https://youtube.com/api/timedtext?v=deep123",
                  languageCode: "tr",
                  name: { simpleText: "Türkçe" },
                  vssId: ".tr",
                },
              ],
            },
          },
        },
        playabilityStatus: { status: "OK" },
      };

      const result = parsePlayerResponse(deeplyNestedPayload);
      expect(result.ok).toBe(true);
      if (!result.ok) {
        return;
      }

      expect(result.value.metadata.videoId).toBe("deep123");
      expect(result.value.captionTracks).toHaveLength(1);
      expect(result.value.captionTracks[0]?.languageCode).toBe("tr");
    });

    it("returns PARSE_ERROR when payload is invalid or empty", () => {
      expect(parsePlayerResponse(null).ok).toBe(false);
      expect(parsePlayerResponse({}).ok).toBe(false);

      const invalidResult = parsePlayerResponse({
        playabilityStatus: { status: "OK" },
      });
      expect(invalidResult.ok).toBe(false);
      if (!invalidResult.ok) {
        expect(invalidResult.error.code).toBe("PARSE_ERROR");
      }
    });
  });

  describe("extractVideoMetadata & extractCaptionTracks", () => {
    it("handles alternative name formats (runs array or direct string)", () => {
      const payload = {
        captions: {
          playerCaptionsTracklistRenderer: {
            captionTracks: [
              {
                baseUrl: "https://yt.com/tt1",
                languageCode: "fr",
                name: { runs: [{ text: "Français" }] },
                kind: "asr",
              },
              {
                baseUrl: "https://yt.com/tt2",
                languageCode: "es",
                name: "Español",
                vssId: "a.es",
              },
            ],
          },
        },
      };

      const tracks = extractCaptionTracks(payload);
      expect(tracks).toHaveLength(2);
      expect(tracks[0]?.name).toBe("Français");
      expect(tracks[0]?.isAutoGenerated).toBe(true);
      expect(tracks[1]?.name).toBe("Español");
      expect(tracks[1]?.isAutoGenerated).toBe(true);
    });

    it("extracts metadata when author is missing but channelTitle is present", () => {
      const payload = {
        videoDetails: {
          videoId: "alt123",
          title: "Alternative Title",
          channelTitle: "Alt Channel",
        },
      };

      const meta = extractVideoMetadata(payload);
      expect(meta).toEqual({
        videoId: "alt123",
        title: "Alternative Title",
        channelName: "Alt Channel",
      });
    });
  });
});
