import { describe, it, expect } from "vitest";
import {
  selectCaptionTrack,
  getOrderedCaptionTracks,
  matchesLanguage,
} from "../src/track-selector.js";
import type { CaptionTrack } from "../src/types.js";

describe("track-selector", () => {
  describe("matchesLanguage", () => {
    it("matches exact codes case-insensitively", () => {
      expect(matchesLanguage("en", "en")).toBe(true);
      expect(matchesLanguage("EN", "en")).toBe(true);
      expect(matchesLanguage("tr", "TR")).toBe(true);
    });

    it("matches regional dialect prefixes", () => {
      expect(matchesLanguage("en-US", "en")).toBe(true);
      expect(matchesLanguage("en", "en-US")).toBe(true);
      expect(matchesLanguage("pt-BR", "pt")).toBe(true);
      expect(matchesLanguage("es", "fr")).toBe(false);
    });

    it("returns false for empty inputs", () => {
      expect(matchesLanguage("", "en")).toBe(false);
      expect(matchesLanguage("en", "")).toBe(false);
    });
  });

  describe("selectCaptionTrack priority hierarchy", () => {
    const tracks: CaptionTrack[] = [
      {
        baseUrl: "https://yt.com/en-manual",
        name: "English (manual)",
        languageCode: "en",
        isAutoGenerated: false,
        isDefault: true,
      },
      {
        baseUrl: "https://yt.com/de-manual",
        name: "German (manual)",
        languageCode: "de",
        isAutoGenerated: false,
        isDefault: false,
      },
      {
        baseUrl: "https://yt.com/es-asr",
        name: "Spanish (auto)",
        languageCode: "es",
        isAutoGenerated: true,
        isDefault: false,
      },
    ];

    it("priority 1: selects user-selected preferred language manual track", () => {
      const selected = selectCaptionTrack(tracks, "de");
      expect(selected?.languageCode).toBe("de");
      expect(selected?.isAutoGenerated).toBe(false);
    });

    it("priority 1b: selects user-selected preferred language auto-generated track if no manual exists", () => {
      const selected = selectCaptionTrack(tracks, "es");
      expect(selected?.languageCode).toBe("es");
      expect(selected?.isAutoGenerated).toBe(true);
    });

    it("priority 2: falls back to video default manual track when preferred language is not found", () => {
      const selected = selectCaptionTrack(tracks, "ja", 0);
      expect(selected?.languageCode).toBe("en");
      expect(selected?.isAutoGenerated).toBe(false);
    });

    it("priority 2: selects default manual track when preferred language is Auto or undefined", () => {
      const selectedWithAuto = selectCaptionTrack(tracks, "auto", 0);
      expect(selectedWithAuto?.languageCode).toBe("en");

      const selectedWithUndefined = selectCaptionTrack(tracks, undefined, 0);
      expect(selectedWithUndefined?.languageCode).toBe("en");
    });

    it("priority 3: selects auto-generated track when no manual tracks exist", () => {
      const autoTracksOnly: CaptionTrack[] = [
        {
          baseUrl: "https://yt.com/fr-asr",
          name: "French (auto)",
          languageCode: "fr",
          isAutoGenerated: true,
          isDefault: false,
        },
        {
          baseUrl: "https://yt.com/en-asr",
          name: "English (auto)",
          languageCode: "en",
          isAutoGenerated: true,
          isDefault: true,
        },
      ];

      const selected = selectCaptionTrack(autoTracksOnly, "auto", 1);
      expect(selected?.languageCode).toBe("en");
      expect(selected?.isAutoGenerated).toBe(true);
    });

    it("priority 4: falls back to first available caption track", () => {
      const unusualTracks: CaptionTrack[] = [
        {
          baseUrl: "https://yt.com/track1",
          name: "Track 1",
          languageCode: "xx",
          isAutoGenerated: false,
          isDefault: false,
        },
      ];

      const selected = selectCaptionTrack(unusualTracks);
      expect(selected?.baseUrl).toBe("https://yt.com/track1");
    });

    it("returns null when tracks array is empty", () => {
      expect(selectCaptionTrack([])).toBeNull();
    });
  });

  describe("getOrderedCaptionTracks ordering and deduplication", () => {
    it("returns an empty array when tracks array is empty", () => {
      expect(getOrderedCaptionTracks([])).toEqual([]);
    });

    it("returns candidate tracks in order: manual track placeholder first, then auto-generated ASR track", () => {
      const dualTracks: CaptionTrack[] = [
        {
          baseUrl: "https://yt.com/tr-manual",
          name: "Turkish",
          languageCode: "tr",
          isAutoGenerated: false,
          isDefault: false,
          vssId: ".tr",
        },
        {
          baseUrl: "https://yt.com/tr-asr",
          name: "Turkish (auto-generated)",
          languageCode: "tr",
          isAutoGenerated: true,
          isDefault: false,
          vssId: "a.tr",
          kind: "asr",
        },
      ];

      const ordered = getOrderedCaptionTracks(dualTracks, undefined, 0);
      expect(ordered).toHaveLength(2);
      expect(ordered[0]?.baseUrl).toBe("https://yt.com/tr-manual");
      expect(ordered[0]?.isAutoGenerated).toBe(false);
      expect(ordered[1]?.baseUrl).toBe("https://yt.com/tr-asr");
      expect(ordered[1]?.isAutoGenerated).toBe(true);
    });

    it("prioritizes user preferred language before video default tracks", () => {
      const multiTracks: CaptionTrack[] = [
        {
          baseUrl: "https://yt.com/tr-manual",
          name: "Turkish (manual)",
          languageCode: "tr",
          isAutoGenerated: false,
          isDefault: true,
        },
        {
          baseUrl: "https://yt.com/en-asr",
          name: "English (auto)",
          languageCode: "en",
          isAutoGenerated: true,
          isDefault: false,
        },
        {
          baseUrl: "https://yt.com/en-manual",
          name: "English (manual)",
          languageCode: "en",
          isAutoGenerated: false,
          isDefault: false,
        },
        {
          baseUrl: "https://yt.com/de-manual",
          name: "German (manual)",
          languageCode: "de",
          isAutoGenerated: false,
          isDefault: false,
        },
      ];

      // Preferred 'en':
      // 1. en-manual (preferred manual)
      // 2. en-asr (preferred auto)
      // 3. tr-manual (video default manual)
      // 4. de-manual (remaining)
      const ordered = getOrderedCaptionTracks(multiTracks, "en", 0);
      expect(ordered.map((t) => t.baseUrl)).toEqual([
        "https://yt.com/en-manual",
        "https://yt.com/en-asr",
        "https://yt.com/tr-manual",
        "https://yt.com/de-manual",
      ]);
    });

    it("deduplicates tracks matching multiple priority criteria", () => {
      const tracks: CaptionTrack[] = [
        {
          baseUrl: "https://yt.com/en-manual",
          name: "English (manual)",
          languageCode: "en",
          isAutoGenerated: false,
          isDefault: true,
        },
        {
          baseUrl: "https://yt.com/en-asr",
          name: "English (auto)",
          languageCode: "en",
          isAutoGenerated: true,
          isDefault: false,
        },
      ];

      // en-manual is: preferred manual, defaultIndex 0, isDefault, first manual
      const ordered = getOrderedCaptionTracks(tracks, "en", 0);
      expect(ordered).toHaveLength(2);
      expect(ordered[0]?.baseUrl).toBe("https://yt.com/en-manual");
      expect(ordered[1]?.baseUrl).toBe("https://yt.com/en-asr");
    });

    it("deduplicates tracks with duplicate baseUrl", () => {
      const duplicateTracks: CaptionTrack[] = [
        {
          baseUrl: "https://yt.com/same-url",
          name: "Track 1",
          languageCode: "en",
          isAutoGenerated: false,
          isDefault: false,
        },
        {
          baseUrl: "https://yt.com/same-url",
          name: "Track 1 Duplicate",
          languageCode: "en",
          isAutoGenerated: false,
          isDefault: false,
        },
      ];

      const ordered = getOrderedCaptionTracks(duplicateTracks);
      expect(ordered).toHaveLength(1);
      expect(ordered[0]?.name).toBe("Track 1");
    });

    it("places auto-generated track in default language before other languages", () => {
      const tracks: CaptionTrack[] = [
        {
          baseUrl: "https://yt.com/tr-manual",
          name: "Turkish (manual)",
          languageCode: "tr",
          isAutoGenerated: false,
          isDefault: true,
        },
        {
          baseUrl: "https://yt.com/es-manual",
          name: "Spanish (manual)",
          languageCode: "es",
          isAutoGenerated: false,
          isDefault: false,
        },
        {
          baseUrl: "https://yt.com/tr-asr",
          name: "Turkish (auto)",
          languageCode: "tr",
          isAutoGenerated: true,
          isDefault: false,
        },
        {
          baseUrl: "https://yt.com/es-asr",
          name: "Spanish (auto)",
          languageCode: "es",
          isAutoGenerated: true,
          isDefault: false,
        },
      ];

      const ordered = getOrderedCaptionTracks(tracks, undefined, 0);
      expect(ordered.map((t) => t.baseUrl)).toEqual([
        "https://yt.com/tr-manual",
        "https://yt.com/tr-asr",
        "https://yt.com/es-manual",
        "https://yt.com/es-asr",
      ]);
    });

    it("prioritizes default auto-generated track over unrelated foreign manual tracks when default track is auto-generated", () => {
      const tracks: CaptionTrack[] = [
        {
          baseUrl: "https://yt.com/fr-manual",
          name: "French (manual)",
          languageCode: "fr",
          isAutoGenerated: false,
          isDefault: false,
        },
        {
          baseUrl: "https://yt.com/en-asr",
          name: "English (auto)",
          languageCode: "en",
          isAutoGenerated: true,
          isDefault: true,
        },
      ];

      const ordered = getOrderedCaptionTracks(tracks, "auto", 1);
      expect(ordered.map((t) => t.baseUrl)).toEqual([
        "https://yt.com/en-asr",
        "https://yt.com/fr-manual",
      ]);
      expect(selectCaptionTrack(tracks, "auto", 1)?.languageCode).toBe("en");
    });

    it("prioritizes exact language match over regional prefix match for preferred language", () => {
      const tracks: CaptionTrack[] = [
        {
          baseUrl: "https://yt.com/en-us-manual",
          name: "English (US)",
          languageCode: "en-US",
          isAutoGenerated: false,
          isDefault: false,
        },
        {
          baseUrl: "https://yt.com/en-manual",
          name: "English",
          languageCode: "en",
          isAutoGenerated: false,
          isDefault: false,
        },
      ];

      const ordered = getOrderedCaptionTracks(tracks, "en");
      expect(ordered.map((t) => t.baseUrl)).toEqual([
        "https://yt.com/en-manual",
        "https://yt.com/en-us-manual",
      ]);
    });

    it("ignores tracks with missing, empty, or whitespace baseUrl", () => {
      const tracks: CaptionTrack[] = [
        {
          baseUrl: "",
          name: "Empty URL Track",
          languageCode: "en",
          isAutoGenerated: false,
          isDefault: false,
        },
        {
          baseUrl: "   ",
          name: "Whitespace URL Track",
          languageCode: "en",
          isAutoGenerated: false,
          isDefault: false,
        },
        {
          baseUrl: "https://yt.com/valid",
          name: "Valid Track",
          languageCode: "en",
          isAutoGenerated: false,
          isDefault: true,
        },
      ];

      const ordered = getOrderedCaptionTracks(tracks);
      expect(ordered).toHaveLength(1);
      expect(ordered[0]?.baseUrl).toBe("https://yt.com/valid");
    });
  });
});
