import { describe, it, expect } from "vitest";
import { selectCaptionTrack, matchesLanguage } from "../src/track-selector.js";
import type { CaptionTrack } from "../src/types.js";

describe("track-selector", () => {
  describe("matchesLanguage", () => {
    it("matches exact codes case-insensitively", () => {
      expect(matchesLanguage("en", "en")).toBe(true);
      expect(matchesLanguage("EN", "en")).toBe(true);
      expect(matchesLanguage("tr", "TR")).toBe(true);
    });

    it("matches regional dialect prefixes", () => {
      expect(matchesLanguage("en-US", "en")).toBe(true);
      expect(matchesLanguage("en", "en-US")).toBe(true);
      expect(matchesLanguage("pt-BR", "pt")).toBe(true);
      expect(matchesLanguage("es", "fr")).toBe(false);
    });

    it("returns false for empty inputs", () => {
      expect(matchesLanguage("", "en")).toBe(false);
      expect(matchesLanguage("en", "")).toBe(false);
    });
  });

  describe("selectCaptionTrack priority hierarchy", () => {
    const tracks: CaptionTrack[] = [
      {
        baseUrl: "https://yt.com/en-manual",
        name: "English (manual)",
        languageCode: "en",
        isAutoGenerated: false,
        isDefault: true,
      },
      {
        baseUrl: "https://yt.com/de-manual",
        name: "German (manual)",
        languageCode: "de",
        isAutoGenerated: false,
        isDefault: false,
      },
      {
        baseUrl: "https://yt.com/es-asr",
        name: "Spanish (auto)",
        languageCode: "es",
        isAutoGenerated: true,
        isDefault: false,
      },
    ];

    it("priority 1: selects user-selected preferred language manual track", () => {
      const selected = selectCaptionTrack(tracks, "de");
      expect(selected?.languageCode).toBe("de");
      expect(selected?.isAutoGenerated).toBe(false);
    });

    it("priority 1b: selects user-selected preferred language auto-generated track if no manual exists", () => {
      const selected = selectCaptionTrack(tracks, "es");
      expect(selected?.languageCode).toBe("es");
      expect(selected?.isAutoGenerated).toBe(true);
    });

    it("priority 2: falls back to video default manual track when preferred language is not found", () => {
      const selected = selectCaptionTrack(tracks, "ja", 0);
      expect(selected?.languageCode).toBe("en");
      expect(selected?.isAutoGenerated).toBe(false);
    });

    it("priority 2: selects default manual track when preferred language is Auto or undefined", () => {
      const selectedWithAuto = selectCaptionTrack(tracks, "auto", 0);
      expect(selectedWithAuto?.languageCode).toBe("en");

      const selectedWithUndefined = selectCaptionTrack(tracks, undefined, 0);
      expect(selectedWithUndefined?.languageCode).toBe("en");
    });

    it("priority 3: selects auto-generated track when no manual tracks exist", () => {
      const autoTracksOnly: CaptionTrack[] = [
        {
          baseUrl: "https://yt.com/fr-asr",
          name: "French (auto)",
          languageCode: "fr",
          isAutoGenerated: true,
          isDefault: false,
        },
        {
          baseUrl: "https://yt.com/en-asr",
          name: "English (auto)",
          languageCode: "en",
          isAutoGenerated: true,
          isDefault: true,
        },
      ];

      const selected = selectCaptionTrack(autoTracksOnly, "auto", 1);
      expect(selected?.languageCode).toBe("en");
      expect(selected?.isAutoGenerated).toBe(true);
    });

    it("priority 4: falls back to first available caption track", () => {
      const unusualTracks: CaptionTrack[] = [
        {
          baseUrl: "https://yt.com/track1",
          name: "Track 1",
          languageCode: "xx",
          isAutoGenerated: false,
          isDefault: false,
        },
      ];

      const selected = selectCaptionTrack(unusualTracks);
      expect(selected?.baseUrl).toBe("https://yt.com/track1");
    });

    it("returns null when tracks array is empty", () => {
      expect(selectCaptionTrack([])).toBeNull();
    });
  });
});
