import { describe, expect, it } from "vitest";
import {
  buildTranscriptArchive,
  createZipPackage,
  strFromU8,
  strToU8,
  unzipSync,
  ZipArchive,
} from "../src/zip.js";
import {
  createExtractionError,
  type ExportManifest,
  type JobItem,
  type Transcript,
  type ZipFileInput,
} from "../src/types.js";

function createMockTranscript(videoId: string, title: string): Transcript {
  return {
    videoId,
    title,
    channelName: "Test Channel",
    language: "en",
    isAutoGenerated: false,
    segments: [
      { start: 0, duration: 2.5, text: "Hello world" },
      { start: 3.0, duration: 1.5, text: "Welcome to testing" },
    ],
  };
}

describe("zip packaging module", () => {
  describe("ZipArchive streaming class", () => {
    it("compresses and packages string and Uint8Array files", async () => {
      const archive = new ZipArchive();

      archive.addFile("greeting.txt", "Hello in-memory zip!");
      archive.addFile("binary.bin", new Uint8Array([1, 2, 3, 4, 5]));

      const zipBytes = await archive.finalize();
      expect(zipBytes).toBeInstanceOf(Uint8Array);
      expect(zipBytes.length).toBeGreaterThan(0);

      const unzipped = unzipSync(zipBytes);
      expect(Object.keys(unzipped).sort()).toEqual([
        "binary.bin",
        "greeting.txt",
      ]);

      expect(strFromU8(unzipped["greeting.txt"] as Uint8Array)).toBe(
        "Hello in-memory zip!"
      );
      expect(Array.from(unzipped["binary.bin"] as Uint8Array)).toEqual([
        1, 2, 3, 4, 5,
      ]);
    });

    it("throws an error when trying to add files to a finalized archive", async () => {
      const archive = new ZipArchive();
      archive.addFile("file1.txt", "Content");
      await archive.finalize();

      expect(() => {
        archive.addFile("file2.txt", "Late content");
      }).toThrow("Cannot add files to a finalized ZipArchive");
    });
  });

  describe("createZipPackage helper", () => {
    it("creates an archive from an array of files", async () => {
      const files: ZipFileInput[] = [
        { filename: "a.txt", content: "File A" },
        { filename: "b.txt", content: strToU8("File B") },
      ];

      const zipData = await createZipPackage(files);
      const unzipped = unzipSync(zipData);

      expect(Object.keys(unzipped).sort()).toEqual(["a.txt", "b.txt"]);
      expect(strFromU8(unzipped["a.txt"] as Uint8Array)).toBe("File A");
      expect(strFromU8(unzipped["b.txt"] as Uint8Array)).toBe("File B");
    });

    it("creates an archive from an async iterable of files", async () => {
      async function* generateFiles(): AsyncIterable<ZipFileInput> {
        yield { filename: "chunk1.txt", content: "Streamed 1" };
        yield { filename: "chunk2.txt", content: "Streamed 2" };
      }

      const zipData = await createZipPackage(generateFiles());
      const unzipped = unzipSync(zipData);

      expect(Object.keys(unzipped).sort()).toEqual([
        "chunk1.txt",
        "chunk2.txt",
      ]);
      expect(strFromU8(unzipped["chunk1.txt"] as Uint8Array)).toBe(
        "Streamed 1"
      );
      expect(strFromU8(unzipped["chunk2.txt"] as Uint8Array)).toBe(
        "Streamed 2"
      );
    });
  });

  describe("buildTranscriptArchive", () => {
    it("packages done items, omits failed/skipped, and includes manifest.json", async () => {
      const items: JobItem[] = [
        {
          videoId: "vid001",
          title: "Introduction to AI",
          status: "done",
        },
        {
          videoId: "vid002",
          title: "Live Q&A Session",
          status: "skipped",
          error: createExtractionError("LIVE_STREAM"),
        },
        {
          videoId: "vid003",
          title: "Advanced ML Tutorial: Part 1?",
          status: "done",
        },
        {
          videoId: "vid004",
          title: "Music Video Without Captions",
          status: "failed",
          error: createExtractionError("NO_CAPTIONS"),
        },
      ];

      const transcriptsMap: Record<string, Transcript> = {
        vid001: createMockTranscript("vid001", "Introduction to AI"),
        vid003: createMockTranscript("vid003", "Advanced ML Tutorial: Part 1?"),
      };

      const result = await buildTranscriptArchive({
        items,
        getTranscript: (videoId) => transcriptsMap[videoId] ?? null,
        format: "markdown",
        channelOrPlaylist: "Tech Channel",
      });

      expect(result.zipData).toBeInstanceOf(Uint8Array);

      // Verify manifest object returned
      expect(result.manifest.summary).toEqual({
        total: 4,
        exported: 2,
        skipped: 1,
        failed: 1,
      });
      expect(result.manifest.channelOrPlaylist).toBe("Tech Channel");

      // Verify unzipped archive
      const unzipped = unzipSync(result.zipData);
      const fileNames = Object.keys(unzipped).sort();

      expect(fileNames).toEqual([
        "1-Introduction-to-AI-vid001.md",
        "3-Advanced-ML-Tutorial-Part-1-vid003.md",
        "manifest.json",
      ]);

      // Verify manifest.json in the zip archive
      const manifestInZipJson = strFromU8(
        unzipped["manifest.json"] as Uint8Array
      );
      const manifestInZip = JSON.parse(manifestInZipJson) as ExportManifest;

      expect(manifestInZip.summary.exported).toBe(2);
      expect(manifestInZip.summary.skipped).toBe(1);
      expect(manifestInZip.summary.failed).toBe(1);
      expect(manifestInZip.items[1]?.error?.code).toBe("LIVE_STREAM");
      expect(manifestInZip.items[3]?.error?.code).toBe("NO_CAPTIONS");

      // Verify transcript file content (markdown)
      const transcript1Content = strFromU8(
        unzipped["1-Introduction-to-AI-vid001.md"] as Uint8Array
      );
      expect(transcript1Content).toContain("# Introduction to AI");
      expect(transcript1Content).toContain("Hello world Welcome to testing");
    });

    it("respects formatOptions such as timestamps for TXT format", async () => {
      const items: JobItem[] = [
        {
          videoId: "t1",
          title: "Timestamp Test",
          status: "done",
        },
      ];

      const result = await buildTranscriptArchive({
        items,
        getTranscript: () => createMockTranscript("t1", "Timestamp Test"),
        format: "txt",
        formatOptions: { includeTimestamps: true },
      });

      const unzipped = unzipSync(result.zipData);
      const txtContent = strFromU8(
        unzipped["1-Timestamp-Test-t1.txt"] as Uint8Array
      );

      expect(txtContent).toContain("[00:00] Hello world");
      expect(txtContent).toContain("[00:03] Welcome to testing");
    });

    it("allows omitting manifest.json when includeManifest is false", async () => {
      const items: JobItem[] = [
        {
          videoId: "v1",
          title: "No Manifest",
          status: "done",
        },
      ];

      const result = await buildTranscriptArchive({
        items,
        getTranscript: () => createMockTranscript("v1", "No Manifest"),
        format: "srt",
        includeManifest: false,
      });

      const unzipped = unzipSync(result.zipData);
      expect(Object.keys(unzipped)).toEqual(["1-No-Manifest-v1.srt"]);
    });

    it("handles empty items list", async () => {
      const result = await buildTranscriptArchive({
        items: [],
        getTranscript: () => null,
        format: "json",
      });

      const unzipped = unzipSync(result.zipData);
      expect(Object.keys(unzipped)).toEqual(["manifest.json"]);
      expect(result.manifest.summary.total).toBe(0);
    });
  });
});
