import { describe, it, expect, vi, beforeEach } from "vitest";
import { MockDocument } from "./mock-dom.js";
import { exportJobZip } from "../src/content/exporter.js";
import type { JobState } from "../src/background/types.js";
import {
  unzipSync,
  strFromU8,
  type Transcript,
} from "@youtube-transcript/core";
import { formatTranscriptStorageKey } from "../src/background/storage.js";

describe("exportJobZip", () => {
  let mockDoc: MockDocument;
  let mockStore: Record<string, unknown>;
  let mockStorageArea: {
    get: ReturnType<
      typeof vi.fn<
        (keys: string | string[]) => Promise<Record<string, unknown>>
      >
    >;
  };

  const mockTranscript1: Transcript = {
    videoId: "vid001",
    title: "Video One",
    channelName: "Test Channel",
    language: "en",
    isAutoGenerated: false,
    segments: [
      { start: 0, duration: 2, text: "Hello world" },
      { start: 2, duration: 3, text: "Welcome to the test" },
    ],
  };

  const mockTranscript2: Transcript = {
    videoId: "vid002",
    title: "Video Two",
    channelName: "Test Channel",
    language: "en",
    isAutoGenerated: true,
    segments: [{ start: 0, duration: 1.5, text: "Second video text" }],
  };

  const mockJob: JobState = {
    id: "job-abc",
    status: "completed",
    channelOrPlaylist: "My Channel",
    createdAt: 1000,
    summary: { total: 2, done: 2, skipped: 0, failed: 0 },
    items: [
      { videoId: "vid001", title: "Video One", status: "done" },
      { videoId: "vid002", title: "Video Two", status: "done" },
    ],
  };

  beforeEach(() => {
    mockDoc = new MockDocument();
    mockStore = {
      [formatTranscriptStorageKey("job-abc", "vid001")]: mockTranscript1,
      [formatTranscriptStorageKey("job-abc", "vid002")]: mockTranscript2,
    };

    mockStorageArea = {
      get: vi.fn(async (keys: string | string[]) => {
        const result: Record<string, unknown> = {};
        const list = Array.isArray(keys) ? keys : [keys];
        for (const k of list) {
          if (mockStore[k] !== undefined) {
            result[k] = mockStore[k];
          }
        }
        return result;
      }),
    };

    // Mock URL.createObjectURL and URL.revokeObjectURL
    if (!globalThis.URL.createObjectURL) {
      globalThis.URL.createObjectURL = vi.fn();
    }
    if (!globalThis.URL.revokeObjectURL) {
      globalThis.URL.revokeObjectURL = vi.fn();
    }
  });

  it("reads transcripts chunk-by-chunk without loading all data simultaneously", async () => {
    const createUrlSpy = vi
      .spyOn(URL, "createObjectURL")
      .mockReturnValue("blob:mock-zip-url");
    const revokeUrlSpy = vi.spyOn(URL, "revokeObjectURL").mockReturnValue();

    const result = await exportJobZip({
      job: mockJob,
      formats: ["txt", "json"],
      storageArea: mockStorageArea,
      doc: mockDoc as unknown as Document,
    });

    expect(result.filename).toBe("My-Channel-export.zip");
    expect(result.manifest.summary.exported).toBe(2);

    // Verify storage was accessed chunk-by-chunk per videoId, NEVER with null
    expect(mockStorageArea.get).toHaveBeenCalledTimes(2);
    expect(mockStorageArea.get).toHaveBeenCalledWith(
      formatTranscriptStorageKey("job-abc", "vid001")
    );
    expect(mockStorageArea.get).toHaveBeenCalledWith(
      formatTranscriptStorageKey("job-abc", "vid002")
    );
    expect(mockStorageArea.get).not.toHaveBeenCalledWith(null);

    // Verify object URL creation and immediate revocation
    expect(createUrlSpy).toHaveBeenCalled();
    expect(revokeUrlSpy).toHaveBeenCalledWith("blob:mock-zip-url");
  });

  it("generates valid zip archive containing manifest.json and transcripts", async () => {
    let capturedBlob: Blob | null = null;
    vi.spyOn(URL, "createObjectURL").mockImplementation((blob: unknown) => {
      capturedBlob = blob as Blob;
      return "blob:test";
    });
    vi.spyOn(URL, "revokeObjectURL").mockImplementation(() => {});

    await exportJobZip({
      job: mockJob,
      formats: ["markdown"],
      channelOrPlaylist: "Science Channel",
      storageArea: mockStorageArea,
      doc: mockDoc as unknown as Document,
    });

    expect(capturedBlob).not.toBeNull();
    if (!capturedBlob) return;

    const arrayBuffer = await (capturedBlob as Blob).arrayBuffer();
    const unzipped = unzipSync(new Uint8Array(arrayBuffer));
    const fileNames = Object.keys(unzipped).sort();

    expect(fileNames).toContain("manifest.json");
    expect(fileNames.some((f) => f.endsWith(".md"))).toBe(true);

    const manifestBytes = unzipped["manifest.json"];
    expect(manifestBytes).toBeDefined();
    if (!manifestBytes) return;

    const manifestContent = JSON.parse(strFromU8(manifestBytes));
    expect(manifestContent.summary.total).toBe(2);
    expect(manifestContent.summary.exported).toBe(2);
    expect(manifestContent.channelOrPlaylist).toBe("Science Channel");
  });

  it("throws descriptive error when storageArea or job is missing", async () => {
    await expect(
      exportJobZip({
        job: null as unknown as JobState,
        storageArea: mockStorageArea,
      })
    ).rejects.toThrow("No job provided for export");

    await expect(
      exportJobZip({
        job: mockJob,
        storageArea: null as unknown as typeof mockStorageArea,
      })
    ).rejects.toThrow("Storage area is not available for export");
  });
});
