import { describe, it, expect, beforeEach, vi } from "vitest";
import {
  MemoryJobStorage,
  ChromeJobStorage,
  formatJobStorageKey,
  formatTranscriptStorageKey,
  ACTIVE_JOB_KEY,
} from "../src/background/storage.js";
import type { JobState } from "../src/background/types.js";
import type { Transcript } from "@youtube-transcript/core";

const mockJob: JobState = {
  id: "job-123",
  status: "running",
  items: [
    { videoId: "v1", title: "Video 1", status: "pending" },
    { videoId: "v2", title: "Video 2", status: "pending" },
  ],
  summary: { total: 2, done: 0, skipped: 0, failed: 0 },
  createdAt: 1000,
};

const mockTranscript: Transcript = {
  videoId: "v1",
  title: "Video 1",
  channelName: "Test Channel",
  language: "en",
  isAutoGenerated: false,
  segments: [{ start: 0, duration: 2.5, text: "Hello world" }],
};

describe("storage", () => {
  describe("MemoryJobStorage", () => {
    let storage: MemoryJobStorage;

    beforeEach(() => {
      storage = new MemoryJobStorage();
    });

    it("saves and retrieves a job state", async () => {
      await storage.saveJob(mockJob);
      const retrieved = await storage.getJob("job-123");
      expect(retrieved).toEqual(mockJob);
    });

    it("returns null for non-existent job", async () => {
      const retrieved = await storage.getJob("non-existent");
      expect(retrieved).toBeNull();
    });

    it("manages active job ID", async () => {
      expect(await storage.getActiveJobId()).toBeNull();
      await storage.setActiveJobId("job-123");
      expect(await storage.getActiveJobId()).toBe("job-123");
      await storage.setActiveJobId(null);
      expect(await storage.getActiveJobId()).toBeNull();
    });

    it("saves and retrieves chunked transcripts per ADR-0002", async () => {
      await storage.saveTranscript("job-123", "v1", mockTranscript);
      const retrieved = await storage.getTranscript("job-123", "v1");
      expect(retrieved).toEqual(mockTranscript);
      expect(await storage.getTranscript("job-123", "unknown")).toBeNull();
    });

    it("retrieves all transcripts for a job via getAllJobTranscripts", async () => {
      await storage.saveTranscript("job-123", "v1", mockTranscript);
      await storage.saveTranscript("job-123", "v2", {
        ...mockTranscript,
        videoId: "v2",
        title: "Video 2",
      });
      await storage.saveTranscript("other-job", "v3", {
        ...mockTranscript,
        videoId: "v3",
      });

      const all = await storage.getAllJobTranscripts("job-123");
      expect(all.size).toBe(2);
      expect(all.has("v1")).toBe(true);
      expect(all.has("v2")).toBe(true);
      expect(all.has("v3")).toBe(false);
    });

    it("clears all job data including transcripts and active id", async () => {
      await storage.saveJob(mockJob);
      await storage.setActiveJobId("job-123");
      await storage.saveTranscript("job-123", "v1", mockTranscript);

      await storage.clearJob("job-123");

      expect(await storage.getJob("job-123")).toBeNull();
      expect(await storage.getActiveJobId()).toBeNull();
      expect(await storage.getTranscript("job-123", "v1")).toBeNull();
    });
  });

  describe("ChromeJobStorage", () => {
    let storage: ChromeJobStorage;
    let mockStore: Record<string, unknown>;

    beforeEach(() => {
      mockStore = {};
      const mockStorageLocal = {
        get: vi.fn(async (keys: unknown) => {
          if (keys === null) {
            return { ...mockStore };
          }
          if (typeof keys === "string") {
            return { [keys]: mockStore[keys] };
          }
          if (Array.isArray(keys)) {
            const res: Record<string, unknown> = {};
            for (const k of keys) {
              res[k] = mockStore[k];
            }
            return res;
          }
          return {};
        }),
        set: vi.fn(async (items: Record<string, unknown>) => {
          Object.assign(mockStore, items);
        }),
        remove: vi.fn(async (keys: string | string[]) => {
          const list = Array.isArray(keys) ? keys : [keys];
          for (const k of list) {
            Reflect.deleteProperty(mockStore, k);
          }
        }),
      };

      vi.stubGlobal("chrome", {
        storage: {
          local: mockStorageLocal,
        },
      });

      storage = new ChromeJobStorage();
    });

    it("persists job under formatted key", async () => {
      await storage.saveJob(mockJob);
      expect(mockStore[formatJobStorageKey("job-123")]).toEqual(mockJob);

      const retrieved = await storage.getJob("job-123");
      expect(retrieved).toEqual(mockJob);
    });

    it("persists active job id under ACTIVE_JOB_KEY", async () => {
      await storage.setActiveJobId("job-123");
      expect(mockStore[ACTIVE_JOB_KEY]).toBe("job-123");
      expect(await storage.getActiveJobId()).toBe("job-123");

      await storage.setActiveJobId(null);
      expect(mockStore[ACTIVE_JOB_KEY]).toBeUndefined();
    });

    it("persists transcript under chunked key", async () => {
      await storage.saveTranscript("job-123", "v1", mockTranscript);
      const expectedKey = formatTranscriptStorageKey("job-123", "v1");
      expect(mockStore[expectedKey]).toEqual(mockTranscript);

      const retrieved = await storage.getTranscript("job-123", "v1");
      expect(retrieved).toEqual(mockTranscript);
    });

    it("clears job and associated transcripts from chrome.storage.local", async () => {
      await storage.saveJob(mockJob);
      await storage.setActiveJobId("job-123");
      await storage.saveTranscript("job-123", "v1", mockTranscript);

      await storage.clearJob("job-123");

      expect(mockStore[formatJobStorageKey("job-123")]).toBeUndefined();
      expect(mockStore[ACTIVE_JOB_KEY]).toBeUndefined();
      expect(
        mockStore[formatTranscriptStorageKey("job-123", "v1")]
      ).toBeUndefined();
    });
  });
});
