export type Segment = {
  start: number;
  duration: number;
  text: string;
};

export type Transcript = {
  videoId: string;
  title: string;
  channelName: string;
  language: string;
  isAutoGenerated: boolean;
  segments: Segment[];
};

export type ExtractionErrorCode =
  | "NO_CAPTIONS"
  | "PRIVATE_OR_MEMBERS"
  | "AGE_RESTRICTED"
  | "LIVE_STREAM"
  | "RATE_LIMITED"
  | "PARSE_ERROR"
  | "UNKNOWN";

export type ExtractionError = {
  code: ExtractionErrorCode;
  message: string;
};

export type JobItemStatus =
  "pending" | "fetching" | "done" | "skipped" | "failed";

export type JobItem = {
  videoId: string;
  title: string;
  status: JobItemStatus;
  error?: ExtractionError;
};

export function createJobItem(videoId: string, title: string): JobItem {
  return {
    videoId,
    title,
    status: "pending",
  };
}
