import type {
  CaptionTrack,
  ExtractionError,
  ExtractionResult,
  ParsedPlayerResponse,
  VideoMetadata,
} from "./types.js";
import { createExtractionError } from "./types.js";

function isRecord(val: unknown): val is Record<string, unknown> {
  return typeof val === "object" && val !== null && !Array.isArray(val);
}

/**
 * Defensively traverses an object tree to locate nodes matching a predicate.
 * Guards against circular references and limits traversal depth.
 */
export function findNodesDeep(
  root: unknown,
  predicate: (key: string, val: unknown) => boolean,
  maxDepth = 20
): unknown[] {
  const matches: unknown[] = [];
  const visited = new Set<unknown>();

  function walk(node: unknown, depth: number): void {
    if (depth > maxDepth || node === null || typeof node !== "object") {
      return;
    }
    if (visited.has(node)) {
      return;
    }
    visited.add(node);

    if (Array.isArray(node)) {
      for (const item of node) {
        walk(item, depth + 1);
      }
      return;
    }

    if (isRecord(node)) {
      for (const [key, val] of Object.entries(node)) {
        if (predicate(key, val)) {
          matches.push(val);
        }
        walk(val, depth + 1);
      }
    }
  }

  walk(root, 0);
  return matches;
}

/**
 * Defensively extracts video metadata (videoId, title, channelName).
 */
export function extractVideoMetadata(payload: unknown): VideoMetadata | null {
  if (!isRecord(payload)) {
    return null;
  }

  // 1. Direct path
  if (isRecord(payload.videoDetails)) {
    const vd = payload.videoDetails;
    const videoId = typeof vd.videoId === "string" ? vd.videoId : "";
    const title = typeof vd.title === "string" ? vd.title : "";
    const channelName =
      typeof vd.author === "string"
        ? vd.author
        : typeof vd.channelTitle === "string"
          ? vd.channelTitle
          : "";

    if (videoId.length > 0) {
      return { videoId, title, channelName };
    }
  }

  // 2. Defensive deep search for an object with videoId and title
  const candidates = findNodesDeep(payload, (key, val) => {
    return (
      key === "videoDetails" && isRecord(val) && typeof val.videoId === "string"
    );
  });

  for (const candidate of candidates) {
    if (isRecord(candidate) && typeof candidate.videoId === "string") {
      const videoId = candidate.videoId;
      const title = typeof candidate.title === "string" ? candidate.title : "";
      const channelName =
        typeof candidate.author === "string"
          ? candidate.author
          : typeof candidate.channelTitle === "string"
            ? candidate.channelTitle
            : "";
      return { videoId, title, channelName };
    }
  }

  return null;
}

/**
 * Defensively extracts captionTracks from player response.
 */
export function extractCaptionTracks(
  payload: unknown,
  defaultCaptionTrackIndex?: number
): CaptionTrack[] {
  if (!isRecord(payload)) {
    return [];
  }

  let rawTracks: unknown[] | null = null;

  // 1. Direct path check
  if (
    isRecord(payload.captions) &&
    isRecord(payload.captions.playerCaptionsTracklistRenderer) &&
    Array.isArray(
      payload.captions.playerCaptionsTracklistRenderer.captionTracks
    )
  ) {
    rawTracks = payload.captions.playerCaptionsTracklistRenderer.captionTracks;
  }

  // 2. Defensive deep search
  if (!rawTracks) {
    const matches = findNodesDeep(payload, (key, val) => {
      return (
        key === "captionTracks" &&
        Array.isArray(val) &&
        val.length > 0 &&
        isRecord(val[0]) &&
        typeof val[0].baseUrl === "string"
      );
    });

    if (matches.length > 0 && Array.isArray(matches[0])) {
      rawTracks = matches[0];
    }
  }

  if (!rawTracks) {
    return [];
  }

  const tracks: CaptionTrack[] = [];

  for (let i = 0; i < rawTracks.length; i++) {
    const raw = rawTracks[i];
    if (!isRecord(raw) || typeof raw.baseUrl !== "string") {
      continue;
    }

    const baseUrl = raw.baseUrl;
    const languageCode =
      typeof raw.languageCode === "string" ? raw.languageCode : "";
    const vssId = typeof raw.vssId === "string" ? raw.vssId : undefined;
    const kind = typeof raw.kind === "string" ? raw.kind : undefined;

    let name = languageCode;
    if (typeof raw.name === "string") {
      name = raw.name;
    } else if (isRecord(raw.name)) {
      if (typeof raw.name.simpleText === "string") {
        name = raw.name.simpleText;
      } else if (
        Array.isArray(raw.name.runs) &&
        raw.name.runs.length > 0 &&
        isRecord(raw.name.runs[0]) &&
        typeof raw.name.runs[0].text === "string"
      ) {
        name = raw.name.runs[0].text;
      }
    }

    const isAutoGenerated =
      kind === "asr" ||
      Boolean(vssId?.startsWith("a.")) ||
      Boolean(vssId?.includes("asr"));

    const isDefault =
      Boolean(raw.isDefault) ||
      (defaultCaptionTrackIndex !== undefined &&
        defaultCaptionTrackIndex === i);

    tracks.push({
      baseUrl,
      name,
      languageCode,
      isAutoGenerated,
      isDefault,
      vssId,
      kind,
    });
  }

  return tracks;
}

/**
 * Extracts default caption track index from audioTracks if present.
 */
function extractDefaultTrackIndex(payload: unknown): number | undefined {
  if (!isRecord(payload)) {
    return undefined;
  }

  if (
    isRecord(payload.captions) &&
    isRecord(payload.captions.playerCaptionsTracklistRenderer) &&
    Array.isArray(payload.captions.playerCaptionsTracklistRenderer.audioTracks)
  ) {
    const audioTracks =
      payload.captions.playerCaptionsTracklistRenderer.audioTracks;
    for (const audio of audioTracks) {
      if (
        isRecord(audio) &&
        typeof audio.defaultCaptionTrackIndex === "number"
      ) {
        return audio.defaultCaptionTrackIndex;
      }
    }
  }

  const matches = findNodesDeep(payload, (key, val) => {
    return key === "defaultCaptionTrackIndex" && typeof val === "number";
  });

  if (matches.length > 0 && typeof matches[0] === "number") {
    return matches[0];
  }

  return undefined;
}

/**
 * Inspects playability status to check for known video errors.
 */
function checkPlayabilityError(
  payload: Record<string, unknown>
): ExtractionError | null {
  const vd = isRecord(payload.videoDetails) ? payload.videoDetails : null;

  // Check for live stream flags
  if (vd) {
    if (vd.isLive === true || vd.isLiveContent === true) {
      return createExtractionError("LIVE_STREAM");
    }
  }

  const ps = isRecord(payload.playabilityStatus)
    ? payload.playabilityStatus
    : null;

  if (!ps) {
    return null;
  }

  const status = typeof ps.status === "string" ? ps.status.toUpperCase() : "";
  const reason = typeof ps.reason === "string" ? ps.reason.toLowerCase() : "";
  const messages = Array.isArray(ps.messages)
    ? ps.messages
        .filter((m): m is string => typeof m === "string")
        .join(" ")
        .toLowerCase()
    : "";
  const combinedReason = `${reason} ${messages}`;

  if (
    status === "LIVE_STREAM_OFFLINE" ||
    combinedReason.includes("live stream")
  ) {
    return createExtractionError("LIVE_STREAM");
  }

  if (status === "LOGIN_REQUIRED") {
    if (
      combinedReason.includes("age") ||
      combinedReason.includes("sign in to confirm your age") ||
      combinedReason.includes("viewer discretion")
    ) {
      return createExtractionError("AGE_RESTRICTED");
    }
    return createExtractionError("PRIVATE_OR_MEMBERS");
  }

  if (status === "UNPLAYABLE" || status === "ERROR") {
    if (combinedReason.includes("age")) {
      return createExtractionError("AGE_RESTRICTED");
    }
    if (
      combinedReason.includes("private") ||
      combinedReason.includes("member") ||
      combinedReason.includes("removed") ||
      combinedReason.includes("deleted") ||
      combinedReason.includes("unavailable")
    ) {
      return createExtractionError("PRIVATE_OR_MEMBERS");
    }
  }

  return null;
}

/**
 * Parses raw InnerTube player response into metadata and caption tracks,
 * mapping failure modes to typed ExtractionError taxonomy.
 */
export function parsePlayerResponse(
  raw: unknown
): ExtractionResult<ParsedPlayerResponse> {
  if (!isRecord(raw)) {
    return {
      ok: false,
      error: createExtractionError(
        "PARSE_ERROR",
        "Player response is not a valid object"
      ),
    };
  }

  // 1. Check playability status for explicit errors (live, age-restricted, private)
  const playabilityError = checkPlayabilityError(raw);
  if (playabilityError) {
    return { ok: false, error: playabilityError };
  }

  // 2. Extract video metadata
  const metadata = extractVideoMetadata(raw);
  if (!metadata) {
    return {
      ok: false,
      error: createExtractionError(
        "PARSE_ERROR",
        "Could not extract video metadata from player response"
      ),
    };
  }

  // 3. Extract caption tracks
  const defaultIndex = extractDefaultTrackIndex(raw);
  const captionTracks = extractCaptionTracks(raw, defaultIndex);

  if (captionTracks.length === 0) {
    return {
      ok: false,
      error: createExtractionError("NO_CAPTIONS"),
    };
  }

  return {
    ok: true,
    value: {
      metadata,
      captionTracks,
      defaultCaptionTrackIndex: defaultIndex,
    },
  };
}
