import type { CaptionTrack } from "./types.js";

/**
 * Checks if a track's language code matches a requested language.
 * Supports exact match and regional prefix matches (e.g. "en" matches "en-US", "en-US" matches "en").
 */
export function matchesLanguage(
  trackLang: string,
  requestedLang: string
): boolean {
  const t = trackLang.trim().toLowerCase();
  const r = requestedLang.trim().toLowerCase();
  if (t.length === 0 || r.length === 0) {
    return false;
  }
  return t === r || t.startsWith(`${r}-`) || r.startsWith(`${t}-`);
}

/**
 * Selects the best caption track according to the priority hierarchy:
 * 1. User-selected preferred language (manual first, then auto-generated)
 * 2. Video default manual track (default index / isDefault flag / first manual)
 * 3. Auto-generated track (default index / isDefault flag / first auto-generated)
 * 4. First available caption track
 */
export function selectCaptionTrack(
  tracks: CaptionTrack[],
  preferredLanguage?: string,
  defaultIndex?: number
): CaptionTrack | null {
  if (tracks.length === 0) {
    return null;
  }

  const pref = preferredLanguage?.trim().toLowerCase();
  const hasPreferred =
    typeof pref === "string" && pref.length > 0 && pref !== "auto";

  // 1. User-selected preferred language
  if (hasPreferred) {
    // 1a. Manual track matching preferred language
    const preferredManual = tracks.find(
      (t) => matchesLanguage(t.languageCode, pref) && !t.isAutoGenerated
    );
    if (preferredManual) {
      return preferredManual;
    }

    // 1b. Auto-generated track matching preferred language
    const preferredAuto = tracks.find(
      (t) => matchesLanguage(t.languageCode, pref) && t.isAutoGenerated
    );
    if (preferredAuto) {
      return preferredAuto;
    }
  }

  // 2. Video default manual track
  // 2a. Track at defaultIndex if manual
  if (
    defaultIndex !== undefined &&
    defaultIndex >= 0 &&
    defaultIndex < tracks.length
  ) {
    const candidate = tracks[defaultIndex];
    if (candidate && !candidate.isAutoGenerated) {
      return candidate;
    }
  }

  // 2b. Track with isDefault flag if manual
  const defaultManual = tracks.find((t) => t.isDefault && !t.isAutoGenerated);
  if (defaultManual) {
    return defaultManual;
  }

  // 2c. First manual track
  const firstManual = tracks.find((t) => !t.isAutoGenerated);
  if (firstManual) {
    return firstManual;
  }

  // 3. Auto-generated track
  // 3a. Track at defaultIndex if auto-generated
  if (
    defaultIndex !== undefined &&
    defaultIndex >= 0 &&
    defaultIndex < tracks.length
  ) {
    const candidate = tracks[defaultIndex];
    if (candidate && candidate.isAutoGenerated) {
      return candidate;
    }
  }

  // 3b. Track with isDefault flag if auto-generated
  const defaultAuto = tracks.find((t) => t.isDefault && t.isAutoGenerated);
  if (defaultAuto) {
    return defaultAuto;
  }

  // 3c. First auto-generated track
  const firstAuto = tracks.find((t) => t.isAutoGenerated);
  if (firstAuto) {
    return firstAuto;
  }

  // 4. First available caption track
  return tracks[0] ?? null;
}
