import type { CaptionTrack } from "./types.js";

/**
 * Checks if a track's language code matches a requested language.
 * Supports exact match and regional prefix matches (e.g. "en" matches "en-US", "en-US" matches "en").
 */
export function matchesLanguage(
  trackLang: string,
  requestedLang: string
): boolean {
  const t = trackLang.trim().toLowerCase();
  const r = requestedLang.trim().toLowerCase();
  if (t.length === 0 || r.length === 0) {
    return false;
  }
  return t === r || t.startsWith(`${r}-`) || r.startsWith(`${t}-`);
}

/**
 * Returns an ordered list of candidate caption tracks according to the priority hierarchy:
 * 1. User-selected preferred language (manual first, then auto-generated)
 * 2. Video default manual track (matching defaultIndex / isDefault / first manual)
 * 3. Video default auto-generated track (matching defaultIndex / isDefault / first auto-generated)
 * 4. Remaining available caption tracks
 * Deduplicates tracks while preserving priority order.
 */
export function getOrderedCaptionTracks(
  tracks: CaptionTrack[],
  preferredLanguage?: string,
  defaultIndex?: number
): CaptionTrack[] {
  if (tracks.length === 0) {
    return [];
  }

  const result: CaptionTrack[] = [];
  const seenTracks = new Set<CaptionTrack>();
  const seenUrls = new Set<string>();

  const add = (track: CaptionTrack | undefined | null) => {
    if (!track) {
      return;
    }
    const cleanUrl = track.baseUrl?.trim();
    if (!cleanUrl) {
      return;
    }
    if (seenTracks.has(track) || seenUrls.has(cleanUrl)) {
      return;
    }
    seenTracks.add(track);
    seenUrls.add(cleanUrl);
    result.push(track);
  };

  const pref = preferredLanguage?.trim().toLowerCase();
  const hasPreferred =
    typeof pref === "string" && pref.length > 0 && pref !== "auto";

  // 1. User-selected preferred language (manual first, then auto-generated)
  // Prioritizes exact language matches over dialect prefix matches
  if (hasPreferred) {
    for (const t of tracks) {
      if (
        t.languageCode.trim().toLowerCase() === pref &&
        !t.isAutoGenerated
      ) {
        add(t);
      }
    }
    for (const t of tracks) {
      if (
        matchesLanguage(t.languageCode, pref) &&
        t.languageCode.trim().toLowerCase() !== pref &&
        !t.isAutoGenerated
      ) {
        add(t);
      }
    }
    for (const t of tracks) {
      if (
        t.languageCode.trim().toLowerCase() === pref &&
        t.isAutoGenerated
      ) {
        add(t);
      }
    }
    for (const t of tracks) {
      if (
        matchesLanguage(t.languageCode, pref) &&
        t.languageCode.trim().toLowerCase() !== pref &&
        t.isAutoGenerated
      ) {
        add(t);
      }
    }
  }

  // Identify the video's default track (defaultIndex if valid, or isDefault flag)
  const defaultTrack =
    (defaultIndex !== undefined &&
      Number.isInteger(defaultIndex) &&
      defaultIndex >= 0 &&
      defaultIndex < tracks.length
      ? tracks[defaultIndex]
      : undefined) ?? tracks.find((t) => t.isDefault);

  // 2. Video default manual track
  let defaultManual: CaptionTrack | undefined;
  if (defaultTrack && !defaultTrack.isAutoGenerated) {
    defaultManual = defaultTrack;
  } else if (defaultTrack) {
    const defaultLang = defaultTrack.languageCode.trim().toLowerCase();
    defaultManual =
      tracks.find(
        (t) =>
          !t.isAutoGenerated &&
          t.languageCode.trim().toLowerCase() === defaultLang
      ) ??
      tracks.find(
        (t) =>
          !t.isAutoGenerated &&
          matchesLanguage(t.languageCode, defaultTrack.languageCode)
      );
  } else {
    defaultManual = tracks.find((t) => !t.isAutoGenerated);
  }
  if (defaultManual) {
    add(defaultManual);
  }

  // 3. Video default auto-generated track
  let defaultAuto: CaptionTrack | undefined;
  if (defaultTrack && defaultTrack.isAutoGenerated) {
    defaultAuto = defaultTrack;
  } else if (defaultTrack) {
    const defaultLang = defaultTrack.languageCode.trim().toLowerCase();
    defaultAuto =
      tracks.find(
        (t) =>
          t.isAutoGenerated &&
          t.languageCode.trim().toLowerCase() === defaultLang
      ) ??
      tracks.find(
        (t) =>
          t.isAutoGenerated &&
          matchesLanguage(t.languageCode, defaultTrack.languageCode)
      );
  } else if (defaultManual) {
    const manualLang = defaultManual.languageCode.trim().toLowerCase();
    defaultAuto =
      tracks.find(
        (t) =>
          t.isAutoGenerated &&
          t.languageCode.trim().toLowerCase() === manualLang
      ) ??
      tracks.find(
        (t) =>
          t.isAutoGenerated &&
          matchesLanguage(t.languageCode, defaultManual.languageCode)
      );
  } else {
    defaultAuto = tracks.find((t) => t.isAutoGenerated);
  }
  if (defaultAuto) {
    add(defaultAuto);
  }

  // 4. Remaining available caption tracks
  for (const t of tracks) {
    add(t);
  }

  return result;
}

/**
 * Selects the best caption track according to the priority hierarchy:
 * 1. User-selected preferred language (manual first, then auto-generated)
 * 2. Video default manual track (default index / isDefault flag / first manual)
 * 3. Auto-generated track (default index / isDefault flag / first auto-generated)
 * 4. First available caption track
 */
export function selectCaptionTrack(
  tracks: CaptionTrack[],
  preferredLanguage?: string,
  defaultIndex?: number
): CaptionTrack | null {
  const ordered = getOrderedCaptionTracks(
    tracks,
    preferredLanguage,
    defaultIndex
  );
  return ordered[0] ?? null;
}
