import type {
  CaptionTrack,
  ExtractionResult,
  Segment,
  Transcript,
  VideoMetadata,
} from "./types.js";
import { createExtractionError } from "./types.js";
import { parsePlayerResponse } from "./player-parser.js";
import { selectCaptionTrack } from "./track-selector.js";
import { parseTimedTextJson } from "./timedtext-parser.js";

export type BuildTranscriptParams = {
  playerPayload: unknown;
  timedTextPayload: unknown;
  preferredLanguage?: string;
};

/**
 * Creates a Transcript object from metadata, selected caption track, and segments.
 */
export function createTranscript(
  metadata: VideoMetadata,
  track: CaptionTrack,
  segments: Segment[]
): Transcript {
  return {
    videoId: metadata.videoId,
    title: metadata.title,
    channelName: metadata.channelName,
    language: track.languageCode,
    isAutoGenerated: track.isAutoGenerated,
    segments,
  };
}

/**
 * Builds a complete normalized Transcript from raw player response and timedtext response.
 */
export function buildTranscript(
  params: BuildTranscriptParams
): ExtractionResult<Transcript> {
  const playerResult = parsePlayerResponse(params.playerPayload);
  if (!playerResult.ok) {
    return playerResult;
  }

  const { metadata, captionTracks, defaultCaptionTrackIndex } =
    playerResult.value;

  const track = selectCaptionTrack(
    captionTracks,
    params.preferredLanguage,
    defaultCaptionTrackIndex
  );

  if (!track) {
    return {
      ok: false,
      error: createExtractionError("NO_CAPTIONS"),
    };
  }

  const timedTextResult = parseTimedTextJson(params.timedTextPayload);
  if (!timedTextResult.ok) {
    return timedTextResult;
  }

  return {
    ok: true,
    value: createTranscript(metadata, track, timedTextResult.value),
  };
}
