export type Segment = {
  start: number;
  duration: number;
  text: string;
};

export type Transcript = {
  videoId: string;
  title: string;
  channelName: string;
  language: string;
  isAutoGenerated: boolean;
  segments: Segment[];
};

export type JobItemStatus =
  "pending" | "fetching" | "done" | "skipped" | "failed";

export type ExtractionErrorCode =
  | "NO_CAPTIONS"
  | "PRIVATE_OR_MEMBERS"
  | "AGE_RESTRICTED"
  | "LIVE_STREAM"
  | "RATE_LIMITED"
  | "PARSE_ERROR"
  | "UNKNOWN";

export type ExtractionError = {
  code: ExtractionErrorCode;
  message: string;
};

export type JobItem = {
  videoId: string;
  title: string;
  status: JobItemStatus;
  error?: ExtractionError;
};

export type CaptionTrack = {
  baseUrl: string;
  name: string;
  languageCode: string;
  isAutoGenerated: boolean;
  isDefault: boolean;
  vssId?: string;
  kind?: string;
};

export type VideoMetadata = {
  videoId: string;
  title: string;
  channelName: string;
};

export type ParsedPlayerResponse = {
  metadata: VideoMetadata;
  captionTracks: CaptionTrack[];
  defaultCaptionTrackIndex?: number;
};

export type ExtractionResult<T> =
  { ok: true; value: T } | { ok: false; error: ExtractionError };

export const EXTRACTION_ERROR_MESSAGES: Record<ExtractionErrorCode, string> = {
  NO_CAPTIONS: "No transcript available",
  PRIVATE_OR_MEMBERS: "Video not accessible",
  AGE_RESTRICTED: "Age-restricted video",
  LIVE_STREAM: "Live stream — skipped",
  RATE_LIMITED: "Rate limited, try again later",
  PARSE_ERROR: "Could not parse response",
  UNKNOWN: "Unexpected error",
};

export function createExtractionError(
  code: ExtractionErrorCode,
  customMessage?: string
): ExtractionError {
  return {
    code,
    message: customMessage ?? EXTRACTION_ERROR_MESSAGES[code],
  };
}

export function createJobItem(videoId: string, title: string): JobItem {
  return {
    videoId,
    title,
    status: "pending",
  };
}

export type ExportFormat = "txt" | "json" | "csv" | "srt" | "vtt" | "markdown";

export type TxtFormatOptions = {
  includeTimestamps?: boolean;
};

export type FormatOptions = TxtFormatOptions;

export type ManifestSummary = {
  total: number;
  exported: number;
  skipped: number;
  failed: number;
};

export type ManifestItem = {
  index: number;
  videoId: string;
  title: string;
  status: JobItemStatus;
  filename?: string;
  error?: ExtractionError;
};

export type ExportManifest = {
  version: "1.0";
  generatedAt: string;
  channelOrPlaylist?: string;
  format?: ExportFormat;
  summary: ManifestSummary;
  items: ManifestItem[];
};

export type ZipFileInput = {
  filename: string;
  content: string | Uint8Array;
};

export type FormatArchiveFileNameOptions = {
  index: number;
  title: string;
  videoId: string;
  format?: ExportFormat;
  ext?: string;
  padWidth?: number;
};

export type BuildTranscriptArchiveParams = {
  items: JobItem[];
  getTranscript: (
    videoId: string
  ) => Promise<Transcript | null | undefined> | Transcript | null | undefined;
  format?: ExportFormat;
  formats?: ExportFormat[];
  formatOptions?: FormatOptions;
  channelOrPlaylist?: string;
  includeManifest?: boolean;
};

export type BuildTranscriptArchiveResult = {
  zipData: Uint8Array;
  manifest: ExportManifest;
};

export type VideoItem = {
  videoId: string;
  title: string;
};

export type AbortSignalLike = {
  readonly aborted: boolean;
};

export type FetchContinuationFn = (
  token: string,
  signal?: AbortSignalLike
) => Promise<unknown>;

export type FetchBrowsePageFn = (request: {
  browseId?: string;
  continuationToken?: string;
  signal?: AbortSignalLike;
}) => Promise<unknown>;

export type EnumerateVideosOptions = {
  browseId?: string;
  initialData?: unknown;
  initialContinuationToken?: string;
  fetchContinuation?: FetchContinuationFn;
  fetchPage?: FetchBrowsePageFn;
  maxDepth?: number;
  maxPages?: number;
  signal?: AbortSignalLike;
};

export type VideosTabInfo = {
  browseId?: string;
  params: string;
  url?: string;
  title?: string;
  selected?: boolean;
  continuationToken?: string;
};

export type PlaylistMetadata = {
  playlistId: string;
  title?: string;
  videoCount?: number;
  author?: string;
  continuationToken?: string;
  initialVideos?: VideoItem[];
};

export type ChannelMetadata = {
  title?: string;
  handle?: string;
  videoCount?: number;
  channelId?: string;
};

export type YouTubeContext = {
  apiKey?: string;
  clientVersion?: string;
  clientName?: string;
  visitorData?: string;
  videosTab?: VideosTabInfo;
  playlist?: PlaylistMetadata;
  channel?: ChannelMetadata;
  initialVideos?: VideoItem[];
};
