export type Segment = {
  start: number;
  duration: number;
  text: string;
};

export type Transcript = {
  videoId: string;
  title: string;
  channelName: string;
  language: string;
  isAutoGenerated: boolean;
  segments: Segment[];
};

export type JobItemStatus =
  "pending" | "fetching" | "done" | "skipped" | "failed";

export type ExtractionErrorCode =
  | "NO_CAPTIONS"
  | "PRIVATE_OR_MEMBERS"
  | "AGE_RESTRICTED"
  | "LIVE_STREAM"
  | "RATE_LIMITED"
  | "PARSE_ERROR"
  | "UNKNOWN";

export type ExtractionError = {
  code: ExtractionErrorCode;
  message: string;
};

export type JobItem = {
  videoId: string;
  title: string;
  status: JobItemStatus;
  error?: ExtractionError;
};

export type CaptionTrack = {
  baseUrl: string;
  name: string;
  languageCode: string;
  isAutoGenerated: boolean;
  isDefault: boolean;
  vssId?: string;
  kind?: string;
};

export type VideoMetadata = {
  videoId: string;
  title: string;
  channelName: string;
};

export type ParsedPlayerResponse = {
  metadata: VideoMetadata;
  captionTracks: CaptionTrack[];
  defaultCaptionTrackIndex?: number;
};

export type ExtractionResult<T> =
  { ok: true; value: T } | { ok: false; error: ExtractionError };

export const EXTRACTION_ERROR_MESSAGES: Record<ExtractionErrorCode, string> = {
  NO_CAPTIONS: "No transcript available",
  PRIVATE_OR_MEMBERS: "Video not accessible",
  AGE_RESTRICTED: "Age-restricted video",
  LIVE_STREAM: "Live stream — skipped",
  RATE_LIMITED: "Rate limited, try again later",
  PARSE_ERROR: "Could not parse response",
  UNKNOWN: "Unexpected error",
};

export function createExtractionError(
  code: ExtractionErrorCode,
  customMessage?: string
): ExtractionError {
  return {
    code,
    message: customMessage ?? EXTRACTION_ERROR_MESSAGES[code],
  };
}

export function createJobItem(videoId: string, title: string): JobItem {
  return {
    videoId,
    title,
    status: "pending",
  };
}

export type ExportFormat =
  | "txt"
  | "json"
  | "csv"
  | "srt"
  | "vtt"
  | "markdown";

export type TxtFormatOptions = {
  includeTimestamps?: boolean;
};

export type FormatOptions = TxtFormatOptions;
